### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by 18z** [spitfire-sidra/mazu#18]
I suggest that we make a todo list for mazu.
So that every member knows what others are doing.
And most importantly, know what to do next. :+1: 

We can do it like https://github.com/deanboole/ssh-chat

**Comment by spitfire-sidra** [comment]
How about using this format for our todo list?

```
## App name

### Models

* [ ] issue

### Views

* [ ] issue

### Templates

* [ ] issue

### Tests

* [ ] issue

### Others
* [ ] issue
```

**Comment by 18z** [comment]
Now we have todo.md for our mazu project! hooray~~

https://github.com/PwnDoRa/mazu/blob/develop/todo.md
