### ISSUE TITLE
add a folder "doc/"

### ISSUE THREAD

**Issue by spitfire-sidra** [spitfire-sidra/mazu#19]
It's worth adding a folder "doc/"! So that, we can write more formal documentation in the folder!

Sphinx-doc is recommended!

**Comment by 18z** [comment]
sure, i'll do that.

**Comment by spitfire-sidra** [comment]
thanks for that!

**Comment by 18z** [comment]
doc directory added

**Comment by spitfire-sidra** [comment]
yeah! go go go!
