### ISSUE TITLE
Should I change the folder name "channel" to "sharing"?

### ISSUE THREAD

**Issue by ghost** [spitfire-sidra/mazu#9]
Actually, the app 'channel' is responsible for sharing samples. For now, mazu can share samples via hpfeeds (https://github.com/rep/hpfeeds). But I think there are several ways to share samples. Maybe the best name of this app is "sharing". How do you think?

**Comment by 18z** [comment]
According to what you said, 

In channel folder, it contains sharing method by using hpfeeds and others methods by other tools (ways).

Am I correct ?

Let's assume that I am right, then I think it would be great to change the folder name from 'channel' to 'sharing'

**Comment by ghost** [comment]
Great! I am working on this issue now!
